USE cea_tp_comanda;

DELETE FROM usuarios;
ALTER TABLE usuarios AUTO_INCREMENT = 1;

DELETE FROM productos;
ALTER TABLE productos AUTO_INCREMENT = 1;

DELETE FROM mesas;
ALTER TABLE mesas AUTO_INCREMENT = 1;

DELETE FROM pedidos;
ALTER TABLE pedidos AUTO_INCREMENT = 1;